lexer grammar CommonLexerRules;

MUL: '*';
DIV: '/';
ADD: '+';
SUB: '-';
EQ: '=';
GREAT: '>';
LESS: '<';
IF: 'if';
ELSE: 'else';
PRINT: 'println';
WHILE: 'while';
FOR: 'for';
INT: 'int';
FLOAT: 'float';
CONST: 'const';
STRING: 'string';
ACHAVE: '{';
FCHAVE: '}';
APAREN: '(';
FPAREN: ')';
VIG: ',';
PTVIG: ';';
ID: [a-zA-Z]+;
INTVAL: [0-9]+;
FLOATVAL: [0-9]+'.'[0-9]+;
STRINGVAL: '"'(.)*?'"';
NEWLINE: '\r'? '\n';
WS: [ \t]+ -> skip;